ASPECTS_CLICKHOUSE_CMS_PASSWORD: ku6TOXXda4A5TMEDI9IOuvgP
ASPECTS_CLICKHOUSE_CMS_USER: ch_cms
ASPECTS_CLICKHOUSE_LRS_PASSWORD: t8ZKPAsFpWxYcl0Py2s3rWCO
ASPECTS_CLICKHOUSE_LRS_USER: ch_lrs
ASPECTS_CLICKHOUSE_REPORT_PASSWORD: a15KvB7P3PQbxZ0XwaRN7lCu
ASPECTS_CLICKHOUSE_REPORT_USER: ch_report
ASPECTS_CLICKHOUSE_VECTOR_PASSWORD: IGIcvKFIKwxHO3zTt4XvywSA
ASPECTS_CLICKHOUSE_VECTOR_USER: ch_vector
CLICKHOUSE_ADMIN_PASSWORD: T5YZkB4Hby1F7dN4g0neXtKa
CLICKHOUSE_ADMIN_USER: ch_admin
CLICKHOUSE_SECURE_CONNECTION: false
CMS_HOST: studio.local.overhang.io
CMS_OAUTH2_SECRET: ZJ0ZTEIjXF2tI0zPFmylaGgN
CODEJAIL_SECRET_KEY: i4Avkllk8dMSixxO1kkurqqC
CONTACT_EMAIL: contact@local.overhang.io
DEV_PROJECT_NAME: gtc_dev
DOCKER_IMAGE_OPENEDX: docker.io/ednxops/public-distro-edxapp:olmo-unesco-v19
ENABLE_HTTPS: false
ID: QPLIvnjCrJJ077xEC1tWSAYv
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEogIBAAKCAQEArszi4I+9un39VlhUw+5MKQuasJkePy8taRC80zF3ThzEarLE

  salyfOJkha5+RZ/Vt+tMQPx/JPd5F34Mb9VjqAkyG86A0WgaJCR5AHcsojoB1Xi4

  4BB4HLfQ4uGNs0mrnGrbdZ7XowKCAQnsSPiN786aMftfUfAP0sVollU6+eCtLxIg

  iHpXrD4KZxbfDrUFwXWOzq9+xH9fKcccE1ZIv0yGQ1ibncAVsrVCFSnyBIEM2luS

  haaL3arb1VTw93Xu5W9EfV7qaFFLl9FsqTAMlfKbD9MQve/F3ElL2Amm7Bfeu7Ov

  BMiBIuMvZvnCV2TT3A9DJSQL7E3kOdiC20dkaQIDAQABAoIBAEjQ38flCQeZeUGR

  TUpLR92nUFq1hjSS7gtA5i/iAM2AzU+XRbmumRst4esQO9i8EvbpJVxC8qIPFxny

  r7KchUWYAxAzT1UsVQtuSBuqCWVQ3bez8Ouh4K8x4WnJxNIFY+AmYWJXd4OXxVky

  bYQeSl41xeUBTn1fD/BgvMc3HPi+71q7SGMrsmXJm3sbzWbarDpBedTYecd0RqlU

  Dz6Nv3KmEFAqgahROqYScyrteKgrkB8UzUm9KIXX+st0nUou9rmx+Msjm/q/2xx7

  OCjwB+5DKcV/bdr0n68UnX1RFJfDIQboKjpJERd4RDRN2W4BBgCXdJEhf39Gdn+3

  MpcOajsCgYEAyNRLFpSvT9v5eZo83NNHeKL5LyBoIuNONfB5Z3EMxk5hdnz38X+f

  tUtDacJhlGYIhO+6z4udc8keCQEL31v9wX5lcahZPiaEwtqItNMFgjtg1M9q3loA

  C28QYutGsmRjFu1SqTaw6pCkRfyRBoa3pmVz4XMWP4gpglahsxxfl38CgYEA3tIO

  zjdAVAfpXuI/Xaq9AeqcFhraf6/UkzGUVCRv2kELEOqxMmWgyE8hAKycBnPkV3MU

  by1+Mp9Ho0wX0CvFguRmMpl+EIhVzpwdNPtsouQVf8klnuTi1ViwNHQXaTrUmo1G

  zF2wyIXYiRRFOZnmhfalr4K+6FKzeE1IEmjzOBcCgYBi4Lszm/MQ46JZ78mlg9S9

  nagIPvFms/mO7x4nAu8iN/ceinrdCVQNw8emK5E1qmLpaMrWYswb9Np33m8FAtrW

  SLATnKqLwhU9hrEmLnuY2jlbrd/VKAS7nGw599LwBCMRZ7l6HLZQVvS6jJau2udS

  4sKCLtK2Zwjg5lxovkCGawKBgDdHf9rTREdUqyYaFURkrn2COfUV9m1FLwTRgQ4a

  +BD6oAczYoCxS+FGGFb1e8PyDo1PhJtMewmOEJTHtQS1R0wA5AXbpLXvTPJ0Mp7J

  XZtP4LGSMp4oBMqPNS/eOUynBsXNFOpwuAIXiq//cmkm8FT96v8O/dPfaJ0I9z9y

  AB1DAoGAWOdx2eQsNUn+kcoYhDLjolJ7A1V/dqy4ZsQTrVtMI+ajYxkzJgD7H/JM

  FPzTFMwgeibV6VqNcWgWKC90xs6w/lx/zJ+cTGtMZgIkkMYIivUlfWJpS+OAcbNN

  tpwi2z0zuMRiqxTxFWMihWKuVDS7A2Rih54uRid7/7NxzLgyvUk=

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: local.overhang.io
LOCAL_PROJECT_NAME: gtc_local
MFE_DOCKER_IMAGE: docker.io/ednxops/ednx-mfe:olmo-20231010-unesco-mfe-extensions
MFE_VALIDATION_PANEL_MFE_APP:
  name: validation-panel
  port: 2001
  repository: https://github.com/edunext/frontend-app-validation-panel.git
  version: master
MYSQL_ROOT_PASSWORD: bf7Uf1Qx
OPENEDX_MYSQL_PASSWORD: MA7tZBsw
OPENEDX_SECRET_KEY: ESQVU8pD1byNCNnU77sP0VG7
PLATFORM_NAME: GTC
PLUGINS:
- mfe
- distro
- codejail
- aspects
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
RALPH_ADMIN_HASHED_PASSWORD: $2b$12$3jZR7dIxhIdXoC4C0Y5yDefebfxyZzEJp1J8dT0Xr.sb.lIBtnMGi
RALPH_ADMIN_PASSWORD: kdpxsnhctamslkpilxppjpiupbogpcpxzndh
RALPH_ADMIN_USERNAME: ralph
RALPH_LMS_HASHED_PASSWORD: $2b$12$YXk9UBCq6SLOJXWclX1c5u3jF0Sewh7AbFDMRHUpJw3dVi3CQ0T9e
RALPH_LMS_PASSWORD: swwztqbvmwzkojtacygjhnodqfphdmxcjbfe
RALPH_LMS_USERNAME: lms
SUPERSET_ADMIN_PASSWORD: N3ycPbrXWbA1GtgnjkG4yUEm
SUPERSET_ADMIN_USERNAME: iim7C6U3MuCB
SUPERSET_DB_PASSWORD: wvq3PpcpHWFoJKUOUsCkcF4g
SUPERSET_OAUTH2_CLIENT_ID: fFH5wtlxqSDuDe0O
SUPERSET_OAUTH2_CLIENT_ID_DEV: GH0X6v9eBFMOzaH1
SUPERSET_OAUTH2_CLIENT_SECRET: HjB8iezOKIQdsUXF
SUPERSET_ROW_LEVEL_SECURITY_XAPI_GROUP_KEY: xapi_course_id
SUPERSET_SECRET_KEY: B8NGrLY5ws3Rg44g4ZTIHWLS
